name: chart_swa_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio: ^5.3.3
  talker_dio_logger: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  riverpod: ^2.4.3
  hooks_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0

  go_router: ^11.1.3

  slang: ^3.24.0
  slang_flutter: ^3.24.0

  flutter_native_splash: ^2.3.3

  flutter_easyloading: ^3.0.5

  adaptive_dialog: ^1.9.0+2
  adaptive_action_sheet: ^2.0.2

  flutter_flavor: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.6

  go_router_builder: ^2.3.3

  freezed: ^2.4.5
  json_serializable: ^6.7.1

  flutter_gen_runner: ^5.3.2

  flutter_launcher_icons: ^0.13.1

  change_app_package_name: ^1.1.0

  riverpod_generator: ^2.3.3
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.1

  slang_build_runner: ^3.24.0

flutter:
  uses-material-design: true
